name: Cypress

on:
  pull_request:
    branches: [ master ]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v4

      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: install dependencies
        run: npm ci

      - name: run Cypress
        run: npm run test
